apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPHostNamespace
metadata:
  name: psp-host-namespace
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
